### ISSUE TITLE
Bug: is not updated daily due to dependencies

### ISSUE THREAD

**Issue by johanla0** [developStorm/simple-badges#34]
### Kind of issue
Bug

### Description
Was not updated to the most recent [9.11.0](https://github.com/simple-icons/simple-icons/releases/tag/9.11.0) although it's been 4 days since the release. 

Readme says it is updated daily, however it is not because `shields` updates dependencies once in a week as stated [here](https://github.com/badges/shields/discussions/5369#discussioncomment-42381). 

Need to simply update readme

**Comment by johanla0** [comment]
Found out it relies on `shield` dependencies, which are scheduled to update each Friday
https://github.com/badges/shields/discussions/5369#discussioncomment-42381

Going to update description and title

**Comment by developStorm** [comment]
Thank you for contributing! Sorry for the delay - I realized that I wasn't watching this repo for some reason, so literally just saw this 😓.
